 const characterInfo = {
   abilities: {
      'Sung-jin-woo': ['Mutilation', 'Shadow Regeneration'],
      'Mikasa': ['Thunder Spears', 'Charge'],
      'Luffy': ['Gum-Gum: Pistol', 'Gear 3'],
      'Gojo': ['Hand-to-hand Combat', 'Limitless'],
      'Natsu': ['Fire Dragon\'s Claws', 'Lightning Fire Dragon'],
      'Ichigo': ['Getsuga Tensho', 'Zanpakuto'],
      'Kakashi': ['Raikiri', 'Sharingan'],
      'Anya': ['Friendship Crash', 'Cuteness Overload'],
      'Mudkip': ['Tackle', 'Mud-Slap'],
      'Genos': ['Incineration Cannon', 'Self-Destruction'],
      'Makima': ['Bang!', 'Contract Holder']
   },
   abilityDamages: {
      'Sung-jin-woo': [160, 200],
      'Mikasa': [80, 120],
      'Luffy': [110, 130],
      'Gojo': [100, 200],
      'Natsu': [120, 130],
      'Ichigo': [0, 10],
      'Kakashi': [150, 200],
      'Anya': [125, 175],
      'Mudkip': [90, 130],
      'Genos': [200, 210],
      'Makima': [95, 135],
   },
   enemyAbilityDamages: {
      'Kirito': [200, 250],
      'Doflamingo': [300, 400],
      'Tanjiro': [240, 280],
      'Escanor': [400, 450],
      'Anderson': [500, 501],
      'Korosensei': [525, 575],
      'Hisoka': [100, 1500],
      'Saitama': [10000, 10001]
   },
   abilityDescription: {
      'Sung-jin-woo': 'Shadows heal allies for a fraction of Sung-jin-woo\'s max health',
      'Mikasa': 'Mikasa\'s next attack has a chance to paralyze the enemy',
      'Luffy': 'Increases Luffy\'s damage for the next 2 rounds (does not stack)',
      'Gojo': 'Gojo distorts space, evading all attacks - duration increases with active allies',
      'Natsu': 'Natsu transforms, increasing damage and having a small chance to paralyze enemies for the next 3 rounds',
      'Ichigo': 'Ichigo summons his Zangetsu and his next attack deals 1/3 of the enemy\'s remaining health',
      'Kakashi': 'Kakashi gets serious, granting him dodge and crit chance for the next three rounds',
      'Anya': 'Anya\'s presence lowers surrounding aggression, permanently decreasing damage of nearby enemies (passive)',
      'Mudkip': 'Mudkip flings mud at the enemy, lowering its accuracy for 1 round',
      'Genos': 'Genos self-destructs, dealing 4 times his remaining health as damage (cannot be used at max health)',
      "Makima": 'Makima forms a contract with the team, equally distributing damage when she is attacked (passive)',
   },
   bgColors: {
      'Kirito': '#0A20A0',
      'Doflamingo': '#cd7cc5',
      'Tanjiro': '#6CCC74',
      'Escanor': '#E29A48',
      'Anderson': '#d8e386',
      'Korosensei': '#E5E632',
      'Hisoka': '#0A0235',
      'Saitama': 'black',
      'Sung-jin-woo': '#7ca7cd',
      'Mikasa': '#cdc17c',
      'Luffy': '#ce3f3f',
      'Gojo': '#dce8a3',
      'Natsu': '#8acd7c',
      'Ichigo': '#cd967c',
      'Kakashi': '#dbdce8',
      'Anya': '#e5a5a5',
      'Mudkip': '#3fcec9',
      'Genos': '#ebad4f',
      'Makima': '#9bdfc3',
   },
   defaultValues: {
      loadout: ['Sung-jin-woo', 'Mikasa', 'Luffy'],
      inventory: ['Gojo', 'Natsu', 'Ichigo', 'Kakashi', 'Anya', 'Mudkip', 'Genos', 'Makima'],
      cardLevels: {
         'Sung-jin-woo': 1,
         'Mikasa': 1,
         'Luffy': 1,
         'Gojo': 1, 'Natsu': 1, 'Ichigo': 1, 'Kakashi': 1, 'Anya': 1, 'Mudkip': 1, 'Genos': 1, 'Makima': 1
      },
      stagesComplete: [],
   },
   health: {
      'Kirito': [2000, 3000, 4000],
      'Doflamingo': [2000, 3500, 4000],
      'Tanjiro': [2000, 4500, 5000],
      'Escanor': [2000, 4000, 7000],
      'Anderson': [2000, 4000, 6000, 9000],
      'Korosensei': [2000, 4000, 6000, 8000, 11000],
      'Hisoka': [2000, 4000, 6000, 8000, 10000],
      'Saitama': [1000, 2000, 3000, 4000, 5000, 8000],
      'Sung-jin-woo': [400, 500, 600, 700, 800, 900],
      'Mikasa': [600, 800, 1000, 1200, 1400, 1600],
      'Luffy': [450, 600, 750, 900, 1050, 1200],
      'Gojo': [450, 600, 750, 900, 1050, 1200],
      'Natsu': [500, 675, 850, 1025, 1200, 1375],
      'Ichigo': [500, 675, 850, 1025, 1200, 1375],
      'Kakashi': [400, 500, 600, 700, 800, 900],
      'Anya': [450, 600, 750, 900, 1050, 1200],
      'Mudkip': [600, 800, 1000, 1200, 1400, 1600],
      'Genos': [500, 675, 850, 1025, 1200, 1375],
      'Makima': [600, 800, 1000, 1200, 1400, 1600],
   },
   bossNames: ['Kirito', 'Doflamingo', 'Tanjiro', 'Escanor', 'Anderson', 'Korosensei', 'Hisoka', 'Saitama'],
   bossDescriptions: ['Black Swordsman', 'Joker', 'Demon Slayer', 'Sin of Pride', 'Father', 'Tentacled Menace', 'Bungee Gum', 'One Punch Man'],
   bossLevels: [1, 2, 2, 3, 4, 5, 5, 6],
   artists: {
      'Kirito': 'SolyWack',
      'Doflamingo': 'Mr0Crocky',
      'Tanjiro': 'Aiqoz',
      'Escanor': 'erwinwin',
      'Anderson': 'NewYa3502',
      'Korosensei': 'Penzoom',
      'Hisoka': 'withacrown',
      'Saitama': 'Steel-Ink',
      'Sung-jin-woo': 'numairbaig',
      'Mikasa': 'SARCHAINNE',
      'Luffy': 'Aiqoz',
      'Gojo': 'SAYA-Team',
      'Natsu': 'NeoZaraki',
      'Ichigo': 'Wguayana',
      'Kakashi': 'TaN1aKa',
      'Anya': 'SAYA-Team',
      'Mudkip': 'NeveDoodle',
      'Genos': 'parthpurwar1',
      'Makima': 'Bryan Thompson',
   },
   artistProfiles: {
      'Kirito': 'https://www.deviantart.com/solywack',
      'Doflamingo': 'https://www.deviantart.com/mr0crocky',
      'Tanjiro': 'https://www.deviantart.com/aiqoz',
      'Escanor': 'https://www.deviantart.com/erwinwin',
      'Anderson': 'https://www.deviantart.com/newya3502',
      'Korosensei': 'https://www.deviantart.com/penzoom',
      'Hisoka': 'https://www.deviantart.com/withacrown',
      'Saitama': 'https://www.deviantart.com/steel-ink',
      'Sung-jin-woo': 'https://www.deviantart.com/numairbaig',
      'Mikasa': 'https://www.deviantart.com/sarchainne',
      'Luffy': 'https://www.deviantart.com/aiqoz',
      'Gojo': 'https://www.deviantart.com/saya-team',
      'Natsu': 'https://www.deviantart.com/neozaraki',
      'Ichigo': 'https://www.deviantart.com/wguayana',
      'Kakashi': 'https://www.deviantart.com/tan1aka',
      'Anya': 'https://www.deviantart.com/saya-team',
      'Mudkip': 'https://www.deviantart.com/nevedoodle',
      'Genos': 'https://www.deviantart.com/parthpurwar1',
      'Makima': 'https://printerval.com/shops/bryan-thompson',
   },
   artLinks: {
      'Kirito': 'https://www.deviantart.com/solywack/art/Sword-Art-Online-Iphone-Shatter-Wallpaper-565667521',
      'Doflamingo': 'https://www.deviantart.com/mr0crocky/art/Donquixote-Doflamingo-158122390',
      'Tanjiro': 'https://www.deviantart.com/aiqoz/art/Tanjiro-Kamado-Kimetsu-no-Yaiba-989038955',
      'Escanor': 'https://www.deviantart.com/erwinwin/art/Escanor-El-pecado-del-orgullo-1003298766',
      'Anderson': 'https://www.deviantart.com/newya3502/art/Alexander-Anderson-Render-958137762',
      'Korosensei': 'https://www.deviantart.com/penzoom/art/Koro-Sensei-650379295',
      'Hisoka': 'https://www.deviantart.com/withacrown/art/Hisoka-fan-art-887199592',
      'Saitama': 'https://www.deviantart.com/steel-ink/art/One-Punch-Man-887886396',
      'Sung-jin-woo': 'https://www.deviantart.com/numairbaig/art/Solo-leveling-Sung-Jin-Woo-in-Royal-Look-1014689615',
      'Mikasa': 'https://www.deviantart.com/sarchainne/art/Mikasa-Ackerman-Attack-On-Titans-993758153',
      'Luffy': 'https://www.deviantart.com/aiqoz/art/Monkey-D-Luffy-One-Piece-990417010',
      'Gojo': 'https://www.deviantart.com/saya-team/art/Nao-Satoru-Gojo-Render-864982182',
      'Natsu': 'https://www.deviantart.com/neozaraki/art/Natsu-Dragneel-vs-Liu-Kang-344832708',
      'Ichigo': 'https://www.deviantart.com/wguayana/art/BLEACH-Ichigo-Kurosaki-998159753',
      'Kakashi': 'https://www.deviantart.com/tan1aka/art/Kakashi-Hatake-907938153',
      'Anya': 'https://www.deviantart.com/saya-team/art/Nao-Anya-Forger-SpyxFamily-Render-920627053',
      'Mudkip': 'https://www.deviantart.com/nevedoodle/art/Mudkip-788834671',
      'Genos': 'https://www.deviantart.com/parthpurwar1/art/Genos-from-One-Punch-Man-Redrawn-Scanned-603310169',
      'Makima': 'https://printerval.com/makima-fanart-chainsaw-man-p41719027',
   }
 }

 export default characterInfo;